print ccm logs

diff --git a/.github/workflows/ci-integration.yml b/.github/workflows/ci-integration.yml
--- a/.github/workflows/ci-integration.yml
+++ b/.github/workflows/ci-integration.yml
@@ -102,18 +102,15 @@ jobs:
             export CCM_VERSION=6.8.23
             export DSE_VERSION=6.8.23
           fi
-          INSTALL_DIR=/tmp/install-dir
-          mkdir /tmp/install-dir
 
           mvn verify -Pmedium -pl pulsar-impl \
             -Ddsbulk.ccm.CCM_VERSION=$CCM_VERSION \
             -Ddsbulk.ccm.CCM_IS_DSE=$CCM_IS_DSE \
             -Ddsbulk.ccm.JAVA_HOME="$JDK8_PATH" \
-            -Ddsbulk.ccm.CCM_DIRECTORY=$INSTALL_DIR \
             -Dpulsar.image=$PULSAR_IMAGE \
             -Dpulsar.image.version=$PULSAR_IMAGE_VERSION \
             -Dmax.ccm.clusters=1 \
-            -DredirectTestOutputToFile=false || (echo "Build failed" && ls -la /tmp/install-dir && cat mkdir /tmp/install-dir/ccm3/node1/logs/debug.log && exit 1)
+            -DredirectTestOutputToFile=false || (echo "Build failed" && find "/tmp/" -name "debug.log" -exec cat {} + && find "/tmp/" -name "system.log" -exec cat {} + && exit 1)
 
       - name: Run integration tests (tests)
         run: |
